const courses = [
    {no: "1", title: "ABC's in ASL: Learn how to Fingerspell!", vid: "va1aAXpVr2w" },
    {no: "2", title: "Numbers 1 through 10 in American Sign Language (ASL)", vid: "ADhWpau22Aw" },
    {no: "3", title: "Start Learning American Sign Language (ASL) Lesson 01 (ASLU)", vid: "kCKFF0Berc8" },
    {no: "4", title: "American Sign Language (ASL) Lesson 01 (narrative story)", vid: "fjIH-u04Ajk" },
    {no: "5", title: "Learn Sign Language: Lesson 01 (ASL)", vid: "DaMjr4AfYA0" },
    {no: "6", title: "ASL Greetings and Polite Phrases", vid: "RlTQEv5I_Y0" },
    {no: "7", title: "American Sign Language (ASL) Lesson 01", vid: "9LtDXSw3e6Y" },
    {no: "8", title: "Pronouns in American Sign Language", vid: "NArwrI2lD-4" },
    {no: "9", title: "American Sign Language (ASL) Lesson 02", vid: "nBhMSjPCfNk" },
    {no: "10", title: "Learn Sign Language: Lesson 02", vid: "U0qG639Vx-0" },
    {no: "11", title: "American Sign Language (ASL) Lesson 02 Narrative", vid: "RVqDPNNQb9M" },
    {no: "12", title: "Lesson 03 (ASL) American Sign Language (slower paced version)", vid: "KZC_eb_3xWk" },
    {no: "13", title: "American Sign Language (ASL) Lesson 03", vid: "r4jsQdoW1bw" },
    {no: "14", title: "American Sign Language (ASL) Lesson 03 (narrative / story)", vid: "496uGsJ_5F4" },
    {no: "15", title: "American Sign Language (ASL) Lesson 04", vid: "JVTsQBVL0eA" },
    {no: "16", title: "American Sign Language (ASL) Lesson 04", vid: "aqdTw1bfkh4" },
    {no: "17", title: "American Sign Language (ASL) Lesson 04 Narrative", vid: "VvO856j3J9A" },
    {no: "18", title: "American Sign Language (ASL) Basic Signing: Lesson 05", vid: "ob0Vg9Mw-4I" },
    {no: "19", title: "ASL signing practice (early beginner)", vid: "9moTwyk2d98" },
    {no: "20", title: "American Sign Language (ASL) Lesson 05", vid: "IKvo4r5ZDWw" },
    {no: "21", title: "American Sign Language (ASL) Lesson 05", vid: "4MWPlmFX8sk" },
    {no: "22", title: "American Sign Language (ASL) Lesson 05 Narrative ", vid: "T3TP65mkfQc" },
    {no: "23", title: "Learn how to count to 30 in ASL (and a fun game)", vid: "4F6rgC1-8rQ" },
    {no: "24", title: "American Sign Language (ASL) Lesson 06", vid: "h8JiHOV8V8I" },
    {no: "25", title: "American Sign Language (ASL) Lesson 06", vid: "smplqw8YTbs" },
    {no: "26", title: "American Sign Language (ASL) Lesson 06 Narrative (Story)", vid: "cDmQLqjn-EQ" },
    {no: "27", title: "American Sign Language (ASL) Lesson 07", vid: "A1vdBurI74" },
    {no: "28", title: "Lesson 08 (Part A and Part B) (introductory paced)", vid: "5RqZRGT3b84" },
    {no: "29", title: "Lesson 08 (parts c and d) (alternate)", vid: "XCWVVQyoqGg" },
    {no: "30", title: "American Sign Language (ASL) Lesson 08 (Part 4)", vid: "pttWES-fR68" },
    {no: "31", title: "Lesson 08", vid: "Xn0F7rGA-3c" },
    {no: "32", title: "American Sign Language (ASL) Lesson 09", vid: "6bsTw2ouTpQ" },
    {no: "33", title: "Lesson 09 (parts a and b)", vid: "S006fguWCl8" },
    {no: "34", title: "Lesson 09 (parts c and d) (alternate)", vid: "n0suOENAy2w" },
    {no: "35", title: "American Sign Language (ASL) Lesson 10 ", vid: "BEWHGV2QIkE" },
    {no: "36", title: "American Sign Language (ASL) Lesson 10 (Version 2", vid: "En4W2_IMS4Y" },
    {no: "37", title: "American Sign Language (ASL) Lesson 11", vid: "UnHm9yoBDJo" },
    {no: "38", title: "Lesson 11 (ASL) (Katelyn) ", vid: "7HlOFxOi6uo" },
    {no: "39", title: "American Sign Language (ASL) Lesson 12", vid: "0OHytO5qxE8" },
    {no: "40", title: "American Sign Language (ASL) Lesson 12", vid: "SbhpRD86JE" },
    {no: "41", title: "Lesson 12, Story A", vid: "hPVzzfWCWNk" },
    {no: "42", title: "Lesson 12 (Story B) ", vid: "kq_Na3EGlLs" },
    {no: "43", title: "American Sign Language (ASL) Lesson 13", vid: "Yf6AMlBm0XY" },
    {no: "44", title: "American Sign Language (ASL) Lesson 13", vid: "rLhirl4zdWo" },
    {no: "45", title: "Lesson 13 (Story B) ", vid: "ZGhRUwA7ti8" },
    {no: "46", title: "American Sign Language (ASL) Lesson 14", vid: "sLDSNdF1wdQ" },
    {no: "47", title: "American Sign Language (ASL) Lesson 14", vid: "uiGEr74JW6k" },
    {no: "48", title: "American Sign Language (ASL) Lesson 14", vid: "OSstg8nlvHU" },
    {no: "49", title: "Fingerspelling Practice", vid: "QK3_0vgmqR4" },
    {no: "50", title: "Lesson 14 (Story)", vid: "h3y-8yHgb_w" },
]
export default courses;